# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_auto_20200122_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='CarMake',
        ),
    ]
