# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_auto_20200122_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.CarMake')),
            ],
        ),
    ]
